[package]
name = "alpha-g-elogger"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/ALPHA-g-Experiment/elogger"
publish = false

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
